repos:
-   repo: local
    hooks:
    -   id: commit-message
        name: check for proper git commit message
        language: pygrep
        entry: '^[\p{Emoji}]:.{0,65}$'
        args: [--multiline]
        stages: [commit-msg]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.11
-   repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile
        name: pip-compile
        args: [requirements.in]
        files: ^requirements\.(in|txt)$