# Generated by Django 5.0.6 on 2024-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("arena", models.TextField(db_column="Arena")),
                ("latitude", models.IntegerField(blank=True, db_column="Latitude", null=True)),
                ("longitude", models.IntegerField(blank=True, db_column="Longitude", null=True)),
                ("capacity", models.IntegerField(blank=True, db_column="Capacity", null=True)),
                ("opened", models.IntegerField(blank=True, db_column="Opened", null=True)),
                ("closed", models.IntegerField(blank=True, db_column="Closed", null=True)),
            ],
            options={
                "db_table": "arena",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "conference",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimDate",
            fields=[
                ("date", models.DateTimeField(primary_key=True, serialize=False)),
                ("season", models.CharField(blank=True, max_length=16, null=True)),
                ("season_phase", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "verbose_name": "Date",
                "verbose_name_plural": "Dates",
                "db_table": "dim_date",
                "ordering": ["-date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "division",
                "ordering": ["conference", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("season", models.CharField(max_length=8, primary_key=True, serialize=False)),
                ("current_yn", models.BooleanField()),
            ],
            options={
                "db_table": "season",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(blank=True, null=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "team",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
