# Generated by Django 5.0.6 on 2024-05-26 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arena",
            options={},
        ),
        migrations.AlterModelOptions(
            name="conference",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dimdate",
            options={"ordering": ["-date"], "verbose_name": "Date", "verbose_name_plural": "Dates"},
        ),
        migrations.AlterModelOptions(
            name="division",
            options={"ordering": ["conference", "name"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
    ]
