# Generated by Django 5.0.6 on 2024-05-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_arena_options_alter_conference_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arena",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.team"),
        ),
        migrations.AddField(
            model_name="division",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="games.conference",
                db_column="conference",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.division", db_column="division"
            ),
        ),
        migrations.AlterField(
            model_name="arena",
            name="arena",
            field=models.CharField(db_column="Arena", max_length=64),
        ),
        migrations.AlterField(
            model_name="conference",
            name="name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
