# Generated by Django 5.0.6 on 2024-05-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_arena_team_division_conference_team_division_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arena",
            name="team",
            field=models.ForeignKey(
                blank=True, db_column="Team", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.team"
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="conference",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.conference"),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.division"),
        ),
    ]
