# Generated by Django 5.0.6 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_arena_team_alter_division_conference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("franchise", models.CharField(db_column="Franchise", max_length=64)),
                ("year_founded", models.IntegerField(blank=True, db_column="Year_Founded", null=True)),
            ],
            options={
                "verbose_name": "Franchise",
                "verbose_name_plural": "Franchises",
                "db_table": "franchise",
                "ordering": ["franchise"],
            },
        ),
    ]
