# Generated by Django 5.0.6 on 2024-05-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_franchise"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="franchise",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.franchise"),
        ),
    ]
