# Generated by Django 5.0.6 on 2025-01-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0007_alter_arena_latitude_alter_arena_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamDatePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("loses", models.IntegerField(blank=True, null=True)),
                ("otl", models.IntegerField(blank=True, null=True)),
                ("sol", models.IntegerField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                (
                    "date",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.dimdate"),
                ),
                (
                    "team",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="games.team"),
                ),
            ],
            options={
                "verbose_name": "Team Date Point",
                "verbose_name_plural": "Team Date Points",
                "db_table": "team_date_point",
                "ordering": ["date", "team"],
            },
        ),
    ]
