# Generated by Django 5.0.6 on 2025-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_teamdatepoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamdatepoint",
            old_name="points",
            new_name="total_points",
        ),
        migrations.AddField(
            model_name="dimdate",
            name="day_of_season",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
