name: Python Script and Publish to Vercel

on:
    workflow_dispatch:
    schedule:
      - cron: 13 4 * * *

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to generate SQLite database
      run: python program.py

    - name: Configure Git
      run: |
        git config --global user.name 'Scheduled Update'
        git config --global user.email 'bot@update.com'

    - name: Commit and Push SQLite Database
      run: |
        git add games.db
        git commit -m "Update SQLite Database"
        git push

    - name: Publish database to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: datasette publish vercel games.db --project=ahl-data --token $VERCEL_TOKEN
